"""initial

Revision ID: 4b9dbc3bc06b
Revises: 
Create Date: 2025-11-29 05:38:34.220570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9dbc3bc06b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('label', sa.String(length=255), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ark_id',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ark_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_id', sa.String(length=256), nullable=True),
    sa.Column('pipeline_id', sa.String(length=64), nullable=True),
    sa.Column('experiment_id', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ark_id')
    )
    op.create_table('dataset_ancestry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parent_dataset_id', sa.String(length=256), nullable=True),
    sa.Column('child_dataset_id', sa.String(length=256), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('parent_dataset_id', 'child_dataset_id', name='uix_1')
    )
    with op.batch_alter_table('dataset_ancestry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_ancestry_child_dataset_id'), ['child_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_ancestry_parent_dataset_id'), ['parent_dataset_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('remoteUrl', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=6), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('date_added_to_portal', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_dataset_id'), ['dataset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_datasets_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_version'), ['version'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('remoteUrl', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=6), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('date_added_to_portal', sa.DateTime(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_experiment_id'), ['experiment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_experiments_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_version'), ['version'], unique=False)

    op.create_table('github_daily_clones_count',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=True),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('timestamp', sa.String(length=30), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('unique_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_daily_views_count',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo', sa.String(length=256), nullable=True),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('timestamp', sa.String(length=30), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('unique_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matomo_daily_dataset_page_views_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.String(length=256), nullable=True),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('nb_hits', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('sum_time_spent', sa.Integer(), nullable=True),
    sa.Column('avg_time_on_page', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matomo_daily_get_page_urls_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('nb_hits', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('sum_time_spent', sa.Integer(), nullable=True),
    sa.Column('avg_time_on_page', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matomo_daily_portal_download_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('nb_hits', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('sum_time_spent', sa.Integer(), nullable=True),
    sa.Column('segment', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matomo_daily_site_keyword_searches_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('avg_time_on_page', sa.Integer(), nullable=True),
    sa.Column('bounce_rate', sa.String(length=64), nullable=True),
    sa.Column('exit_nb_visits', sa.Integer(), nullable=True),
    sa.Column('exit_rate', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('nb_hits', sa.Integer(), nullable=True),
    sa.Column('nb_pages_per_search', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('sum_time_spent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matomo_daily_visits_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.Column('avg_time_on_site', sa.Integer(), nullable=True),
    sa.Column('bounce_count', sa.Integer(), nullable=True),
    sa.Column('max_actions', sa.Integer(), nullable=True),
    sa.Column('nb_actions', sa.Integer(), nullable=True),
    sa.Column('nb_actions_per_visit', sa.Float(), nullable=True),
    sa.Column('nb_uniq_visitors', sa.Integer(), nullable=True),
    sa.Column('nb_users', sa.Integer(), nullable=True),
    sa.Column('nb_visits', sa.Integer(), nullable=True),
    sa.Column('nb_visits_converted', sa.Integer(), nullable=True),
    sa.Column('sum_visit_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('version', sa.String(length=128), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelines_is_private'), ['is_private'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pipelines_pipeline_id'), ['pipeline_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_pipelines_version'), ['version'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), server_default='', nullable=False),
    sa.Column('label', sa.String(length=255), server_default='', nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('email_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=256), server_default='', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('full_name', sa.String(length=64), server_default='', nullable=False),
    sa.Column('affiliation', sa.String(length=128), nullable=True),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('affiliation_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['affiliation_type_id'], ['affiliation_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('flask_dance_oauth',
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('provider_user_login', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_table('users_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_roles')
    op.drop_table('flask_dance_oauth')
    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelines_version'))
        batch_op.drop_index(batch_op.f('ix_pipelines_pipeline_id'))
        batch_op.drop_index(batch_op.f('ix_pipelines_owner_id'))
        batch_op.drop_index(batch_op.f('ix_pipelines_name'))
        batch_op.drop_index(batch_op.f('ix_pipelines_is_private'))

    op.drop_table('pipelines')
    op.drop_table('matomo_daily_visits_summary')
    op.drop_table('matomo_daily_site_keyword_searches_summary')
    op.drop_table('matomo_daily_portal_download_summary')
    op.drop_table('matomo_daily_get_page_urls_summary')
    op.drop_table('matomo_daily_dataset_page_views_summary')
    op.drop_table('github_daily_views_count')
    op.drop_table('github_daily_clones_count')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_version'))
        batch_op.drop_index(batch_op.f('ix_experiments_name'))
        batch_op.drop_index(batch_op.f('ix_experiments_is_private'))
        batch_op.drop_index(batch_op.f('ix_experiments_experiment_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_version'))
        batch_op.drop_index(batch_op.f('ix_datasets_name'))
        batch_op.drop_index(batch_op.f('ix_datasets_is_private'))
        batch_op.drop_index(batch_op.f('ix_datasets_dataset_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('dataset_ancestry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_ancestry_parent_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_ancestry_child_dataset_id'))

    op.drop_table('dataset_ancestry')
    op.drop_table('ark_id')
    op.drop_table('affiliation_type')
    # ### end Alembic commands ###
